### ISSUE TITLE
Wrong spatialplot of Affine Transformation

### ISSUE THREAD

**Issue by jefferyUstc** [scverse/spatialdata-plot#103]
With this issue  (#101 ) addressed, I run the tutorial **Transformations and coordinate systems**, https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/transformations.html

totally following the tutorial, when it comes to the affine transformation, it got wrong spatialplot.

```
theta = math.pi / 6
rotation = Affine(
    [
        [math.cos(theta), -math.sin(theta), 0],
        [math.sin(theta), math.cos(theta), 0],
        [0, 0, 1],
    ],
    input_axes=("x", "y"),
    output_axes=("x", "y"),
)

set_transformation(sdata.images["raccoon"], rotation, to_coordinate_system="global")

sdata.pl.render_images().pl.render_labels().pl.render_shapes().pl.show()
```
<img width="524" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/44384930/57ced279-8e72-44af-98a8-b87e4a02ce67">

FYI:

```
(spatialdata) $ pip list | grep spatialdata

napari-spatialdata            0.2.4
spatialdata                   0.0.10
spatialdata-io                0.0.4
spatialdata-plot              0.0.0  ## pip install the version from spatialdata-plot@bugfix/issue100-get_extent-produces-wrong-output-after-spatial-query
```

**Comment by timtreis** [comment]
Hey @jefferyUstc, thanks for reporting this! We also noticed this yesterday, I'm working with @LucaMarconato on a fix for this (https://github.com/scverse/spatialdata/issues/296). I'll ping you when it's fixed 💪
