### ISSUE TITLE
Legend coloring doesn't match with plot in `render_shapes`

### ISSUE THREAD

**Issue by timtreis** [scverse/spatialdata-plot#104]
MRE
```
f, ax = plt.subplots(figsize=(7, 7))
sdata_ST8059048.pl.render_shapes(color="library", palette="Pastel1").pl.show(ax=ax)
cropped_sdata.pl.render_shapes(color="Sox2").pl.show(ax=ax, colorbar=False)

# show the spatial query bounding box
rect = patches.Rectangle((8000, 12000), 4000, 4000, linewidth=5, edgecolor="k", facecolor="none")
ax.add_patch(rect)

```

<img width="781" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/12818242/6dfcacf9-1500-4699-8ec4-f9a6f424a859">

**Comment by LucaMarconato** [comment]
I also noticed that in the new [aggregation notebook](https://github.com/scverse/spatialdata-notebooks/blob/main/notebooks/examples/aggregation.ipynb).

I define some categorical annotations: `"categorical": ["a", "a", "b", "c", "d"],`, but when I plot them the `a` category is colored only once, while the `d` is colored twice.

<img width="368" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/2664412/46b13248-ea11-4307-bee3-b6489278dae6">
