### ISSUE TITLE
Cannot plot values from the columns of a `GeoDataFrame`

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#105]
If we have a `GeoDataFrame` with say, one categorical column on it, and we set `color='column_name'`, we get this error `KeyError: 'Could not find key type in .var_names or .obs.columns.'` because the code only looks in the table.

This can be easily fixed using this function (not in main yet but will be there very soon) https://github.com/scverse/spatialdata/blob/2bd82d73243fc1337dc15d95a110b51be84576eb/src/spatialdata/_core/query/relational_query.py#L207

The function looks for the requested value from any place (dataframe columns, var, obs) and throws exceptions when the column is not found or is found in multiple places. You can request single columns or multiple numerical columns (as a list of column names).

Limtiations:
- it throws an error if you try to request multiple categorical variables
- it throws an error if you ask multiple columns that are not from the same location (e.g. one column from obs and one from var_names)

If these limitations are too strict I can relax them.

**Comment by LucaMarconato** [comment]
To reproduce run this (to see how the plot should look like change the if from `True` to `False`). Plot shown also down in the pic.

```python
import pandas as pd
from shapely import linearrings, polygons
import geopandas as gpd
from spatialdata.models import ShapesModel, TableModel
from anndata import AnnData
import spatialdata_plot
import matplotlib.pyplot as plt
import numpy as np
from spatialdata import SpatialData

# pre-commits would delete unused imports
_ = spatialdata_plot


def _make_squares(centroid_coordinates: np.ndarray, half_widths: list[float]) -> polygons:
    linear_rings = []
    for centroid, half_width in zip(centroid_coordinates, half_widths):
        min_coords = centroid - half_width
        max_coords = centroid + half_width

        linear_rings.append(
            linearrings(
                [
                    [min_coords[0], min_coords[1]],
                    [min_coords[0], max_coords[1]],
                    [max_coords[0], max_coords[1]],
                    [max_coords[0], min_coords[1]],
                ]
            )
        )
    s = polygons(linear_rings)
    polygon_series = gpd.GeoSeries(s)
    cell_polygon_table = gpd.GeoDataFrame(geometry=polygon_series)
    return ShapesModel.parse(cell_polygon_table)


square = _make_squares(np.atleast_2d([5, 5]), half_widths=[5])
little_squares = _make_squares(
    np.atleast_2d([[0.5, 0.5], [1.5, 0.5], [2.5, 0.5], [3.5, -1 / 6.0], [4.5, -1 / 6.0]]),
    half_widths=[0.5, 0.5, 0.5, 0.5, 0.5],
)

if False:
    little_squares['type'] = ['A', 'A', 'A', 'B', 'B']
    table = None
else:
    table = AnnData(shape=(5, 0), obs=pd.DataFrame({'type': ['A', 'A', 'A', 'B', 'B']}))
    table.obs['type'] = table.obs['type'].astype('category')
    table.obs['region'] = 'little_squares'
    table.obs['region'] = table.obs['region'].astype('category')
    table.obs['instance_id'] = [0, 1, 2, 3, 4]
    table = TableModel.parse(table, region='little_squares', region_key='region', instance_key='instance_id')

ax = plt.gca()
test_sdata = SpatialData(shapes={"square": square, "little_squares": little_squares}, table=table)
test_sdata.pl.render_shapes("square").pl.show(ax=ax)
test_sdata.pl.render_shapes("little_squares", color='type').pl.show(ax=ax)

# set limits
ax.set_xlim(-1, 7)
ax.set_ylim(-1, 7)

# set ticks
ax.set_xticks(range(-1, 12))
ax.set_yticks(range(-1, 12))

# show axes
ax.axhline(0, color="black", linewidth=0.5)
ax.axvline(0, color="black", linewidth=0.5)

# set labels
ax.set_xlabel("x")
ax.set_ylabel("y")

# show grid
ax.grid(True)
ax.set_title("ehi")

plt.show()
```

![image](https://github.com/scverse/spatialdata-plot/assets/2664412/b6ca199c-afd2-463a-82f9-5dd71e73953e)

**Comment by timtreis** [comment]
Sounds good, happy to implement once it's merged into main. I think the limitations are fine as well, in the `spatialdata-plot` usecase, the user shouldn't specify more than one column to color by anyway.

**Comment by MobiTobi** [comment]
This bug also breaks the [spatial_query tutorial](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/spatial_query.html).
 
 ```
sdata.pl.render_shapes(color="library").pl.show()
```

**Comment by timtreis** [comment]
<img width="695" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/12818242/6d96c0aa-ac9a-4636-964a-54abede2befe">
Almost fixed, but I'll do the multipolygon issue in this PR too

**Comment by LucaMarconato** [comment]
🚀🚀
