### ISSUE TITLE
Alpha is ignored for shapes

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#107]
In the new [aggregation notebook](https://github.com/scverse/spatialdata-notebooks/blob/main/notebooks/examples/aggregation.ipynb), this block of code:

```python
ax = plt.gca()

sdata_squares.pl.render_shapes("squares", na_color="red", alpha=0.5).pl.show(ax=ax)
sdata_circles.pl.render_shapes("blobs_circles", alpha=0.5).pl.show(ax=ax)
```

gives this
![image](https://github.com/scverse/spatialdata-plot/assets/2664412/153a980f-6465-4d68-9086-65ddb9b44c06)

As it can be seen the alpha is not correctly displayed. I think it was fixed at some point, maybe the bug fell through again.

**Comment by timtreis** [comment]
That's because the parameter is called `fill_alpha` to separate it from the `outline_alpha` one 👍

**Comment by timtreis** [comment]
Noticed that the documentation is out of date on this one though, will open a separate issue for this
