### ISSUE TITLE
cmap argument without effect

### ISSUE THREAD

**Issue by MobiTobi** [scverse/spatialdata-plot#115]
When plotting array data the `cmap` argument has no effect.
Expected behavriour would be application of the viridis or Reds colormap instead of default Blues.
```
import spatialdata_plot
from spatialdata.datasets import blobs
import matplotlib.pyplot as plt

sdata = blobs()

fig, axs = plt.subplots(ncols=3, figsize=(12, 3))
sdata.pl.render_images("blobs_image", channel=0).pl.show(ax=axs[0])
sdata.pl.render_images("blobs_image", channel=0, cmap='viridis').pl.show(ax=axs[1])
sdata.pl.render_images("blobs_image", channel=0, cmap='Reds').pl.show(ax=axs[2])
```
<img width="867" alt="Screenshot 2023-06-29 at 13 01 37" src="https://github.com/scverse/spatialdata-plot/assets/8470963/edc50d70-9e73-4561-abdb-9c3286bcfaa3">

**Comment by timtreis** [comment]
Fixed in https://github.com/scverse/spatialdata-plot/pull/111
