### ISSUE TITLE
RGB bug with data range (raccoon changed color)

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#126]
The raccoon in the transformation notebook changed colors:
<img width="1882" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/2664412/efda04ad-60b6-4ad6-ac3e-18d368c2aa40">
showing this warning:
```
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
```

**Comment by timtreis** [comment]
ughhhh this palette blending is a nightmare
