### ISSUE TITLE
 Reading highly resolved image

### ISSUE THREAD

**Issue by sokratiag** [scverse/spatialdata-plot#128]
Hello,

Many thanks for this nice tool! 

I am wondering if it is possible to work with the full resolution image, for example to use squidpy to extract image features from the full resolution. I tried the the tutorial you provide with the breast cancer data, but when I try to visiualise the 'global' image  (adata.pl.render_images().pl.render_shapes().pl.show("global") I get an  index error. 

[spatialdata.md](https://github.com/scverse/spatialdata/files/12196364/spatialdata.md)

Thanks,

Sokratia

**Comment by timtreis** [comment]
@sokratiag Hey there! Thanks for pointing out this issue. @Sonja-Stockhaus just linked a PR which hopefully fixes it, would you mind confirming that by cloning that branch from GitHub and trying?

You can do that with 
```
git clone git@github.com:scverse/spatialdata-plot.git
cd spatialdata-plot
git checkout bugfix/issue128-reading-highly-resolved-image 
git pull
pip install .
```
