### ISSUE TITLE
Outline width in render_shapes is ignored

### ISSUE THREAD

**Issue by marcovarrone** [scverse/spatialdata-plot#136]
The function `pl.render_shapes` accepts `outline_width` as a parameter.
This parameter accepts a tuple `(bg_size, gap_size)`. What is the meaning of the two values in the context of shapes' outlines?

More importantly, unless I overlooked some code, the `bg_size` and `gap_size` values of the `OutlineParams` class are not used anywhere. In fact, in `pl.render_shapes` there is a fixed width for the shape outlines.
https://github.com/scverse/spatialdata-plot/blob/19bc0835133abd61c2fa9cbfb0b6d561425bf762/src/spatialdata_plot/pl/render.py#L157

**Comment by timtreis** [comment]
@Sonja-Stockhaus 

todo:
- replace tuple with float
- use float
