### ISSUE TITLE
Wrong colormap for H&E

### ISSUE THREAD

**Issue by marcovarrone** [scverse/spatialdata-plot#140]
Hello, maybe I am doing something wrong because I thought this problem would not occur after #127.
When I follow the tutorial on the [Visium dataset](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/technology_visium.html) and I plot the H&E image with the code shown in the tutorial I get the following image:
![image](https://github.com/scverse/spatialdata-plot/assets/9199935/3c75aa54-8e72-4e92-b4f3-b0e74343cc26).

I checked and my version of spatialdata_plot contains the edit done in that pull request.
Cheers!

**Comment by timtreis** [comment]
Hey @marcovarrone, which plot would you expect? I think we haven't updated the tutorial notebook after #127, so that could explain the difference?

**Comment by marcovarrone** [comment]
If you plot the image using `matplotlib`, it shows the sample in the way the H&E usually looks like.

`plt.imshow(np.transpose(np.array(sdata.images["ST8059048_image"]), axes=(1,2,0)))`

So this:
![image](https://github.com/scverse/spatialdata-plot/assets/9199935/70dbc467-2545-4688-a9cd-e067e4b91e90)

**Comment by timtreis** [comment]
Oh weird 🤔 My go-to check for this was always our `raccoon` picture which now still has the correct colors. I'll try to figure out why our H&E looks different  
![image](https://github.com/scverse/spatialdata-plot/assets/12818242/5c534492-8aaf-442e-a52f-f492f2a9c34e)

**Comment by marcovarrone** [comment]
Thank you very much for looking into it! 
I also tried with my own H&E image and I got the same problem.

**Comment by LucaMarconato** [comment]
It could be maybe to an alpha channel present in the H&E image that makes the plot escapes some if conditions? @marcovarrone could you please try with a rgb version of the H&E image, if it is a rgba image?

**Comment by giovp** [comment]
hitting the same issue, @timtreis could you please take a look, it's rather weird as it should just use plt.imshow int he backed and I'm fairly confident that at first release this was working correctly so it must have been something introduces later on.

@marcovarrone you can try something like this for the time being
```python
gene = "TAS1R1"
fig, ax = plt.subplots(1,1,figsize=(10,10))
ax.imshow(sdatas["ht232p1h1a2"].images["ht232p1h1a2_image"].transpose("y","x","c"))
sdatas["ht232p1h1a2"].pl.render_shapes(color=gene, layer="X").pl.show(ax=ax)
```
![image](https://github.com/scverse/spatialdata-plot/assets/25887487/6b4ec035-b87e-48d9-a5d5-0b1bbbd7ccb6)
