### ISSUE TITLE
palette argument has no effect on plotting colors in pl.render_shapes()

### ISSUE THREAD

**Issue by sopvdl** [scverse/spatialdata-plot#145]
Hi there, thanks for this great tool! Super useful so far, but I'm running into some issues trying specify colors for categorical values with `pl.render_shapes()`.

Specifying colors with the `palette` argument, I get my desired colors in the legend but not in the plot itself. 

```
sdata.pl.render_shapes('cell_boundaries', color='graphclust', palette=ListedColormap(['blue', 'red']), groups=['2', '9']).pl.show(ax=ax, title='clusters')
```
<img src="https://github.com/scverse/spatialdata-plot/assets/117607744/e0eb5110-81d1-4008-b71c-d61a75f1fb99" width="500" >

I've tried many things, also without the `groups` argument but so far haven't been able to use `palette` to specify colors for categorical values in the plot itself. Would be great to be able to do this because the standard colors can be hard to see :)

**Comment by LucaMarconato** [comment]
@sopvdl the issue should be fixed now using the latest `main` version of `spatialdata-plot`.

**Comment by sopvdl** [comment]
Awesome thanks for the fix it's working now! 

But I do notice when I'm now plotting with the `groups` argument, the `na_color` argument doesn't seem to be working anymore. As in the cells that are not in the groups will not be plotted and specifying a color with `na_color` has no effect. Are you also seeing this?

**Comment by timtreis** [comment]
Yeah, can reproduce. Will open a new ticket for it

**Comment by timtreis** [comment]
Yes, this is actually the intended behaviour for `groups`, analog to `scanpy` or `squidpy`
