### ISSUE TITLE
`_robust_transform()` after cropping gives problems with images and labels

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#167]
Probably this bug will disappear once https://github.com/scverse/spatialdata/pull/318 is merged.

I have noticed that if I do a bounding box query on the `blobs` dataset, and I try to plot the shapes, I get an error related to the images and labels (btw strange, since I was not trying to plot raster data).

This can be reproduced as follows:

```python
import spatialdata as sd
from spatialdata.models import TableModel
from spatialdata.datasets import blobs
import spatialdata_plot
from napari_spatialdata import Interactive
import numpy as np

sdata = blobs()

sdata_cropped = sdata.query.bounding_box(axes=('x', 'y'), min_coordinate=[200, 150], max_coordinate=[300, 250], target_coordinate_system='global')
sdata_cropped

# del sdata_cropped.images['blobs_image']
# del sdata_cropped.images['blobs_multiscale_image']
# del sdata_cropped.labels['blobs_labels']
# del sdata_cropped.labels['blobs_multiscale_labels']

sdata_cropped.pl.render_shapes('blobs_circles').pl.show()
```

The last line will fail, but if we uncomment the 4 lines with `del`, which remove raster data from the `sdata_cropped` object, then plotting will work.

**Comment by Sonja-Stockhaus** [comment]
@LucaMarconato I also noticed that there are bugs in this function, the problem is when it gets multi-scale images as input or labels with only [y, x] and not [c, y, x]. I made some adjustments to the function so I hope the problem is gone when multiscale-image handling is finished (https://github.com/scverse/spatialdata-plot/pull/164)

**Comment by timtreis** [comment]
Yeah, I'd prefer not to fix `robust_transform` as it'll soon disappear. I'm just waiting for the fix of https://github.com/scverse/spatialdata/issues/353 to finalise the https://github.com/scverse/spatialdata/pull/318. Afterwards we plan to also do a release of `spatialdata-plot` 👍

**Comment by timtreis** [comment]
`_robust_transform` is no longer part of the codebase since https://github.com/scverse/spatialdata-plot/pull/162
