### ISSUE TITLE
Why does the API require repeated `.pl` in a plotting command

### ISSUE THREAD

**Issue by grst** [scverse/spatialdata-plot#213]
Hi all, 

I was wondering about the API design of spatialdata-plot: Why did you decide for requiring a `pl` before every plotting command in a "plotting pipeline", e.g. 

```python
sdata.pl.render_images().pl.render_shapes(color="KRAS").pl.show("downscaled_hires")
```

instead of just once to instantiate a plot object

```python
sdata.pl.render_images().render_shapes(color="KRAS").show("downscaled_hires")
```

To me, this feels redundant and harder to read especially when the plotting commands become longer than the example above.

**Comment by melonora** [comment]
Please see #54, closing this one for now as being duplicate, but please know I am aware but it requires some refactoring. Will try to find the time.
