### ISSUE TITLE
Priorities 21-03

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata-plot#22]
### Description of feature

- [x] P0 dealing with transformations (racoon example) @timtreis 
- [x] P0 dealing with coordinate systems (xenium and visium) @timtreis 
- [ ] P0 API docs tbd
- [x] P0 Xenium (plotting transcripts) @timtreis 
- [x] P0 Color shapes/labels by a column in the table, exp gene expression @timtreis 
- [x] P0 Codex (mcmicro) @sagar87 
- [x] P0 Visium @sagar87 
- [ ] P1 examples running in CI and being rendered and link in sphinx
- [ ] P1 neighbourhood graph plotting

**Comment by LucaMarconato** [comment]
@timtreis does this work already? Neighbourhood graph plotting

**Comment by timtreis** [comment]
No, closed the issue because it was so old. I have a HiWi starting soon that I'll have work on these more major changes (backend, `render_graph` or sth?). But before I'd want to get a release out
