### ISSUE TITLE
Plotting categorical variables to shapes stopped working

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#228]
There was some major refactoring recently, it seems that plotting a categorical variable to shapes stopped working. 

```python
import spatialdata_plot
import matplotlib.pyplot as plt
from spatialdata.datasets import blobs_annotating_element

sdata = blobs_annotating_element('blobs_circles')
sdata['table'].obs['category'] = ['a', 'b', 'c', 'a', 'b']


sdata.pl.render_shapes('blobs_circles', color='category').pl.show()
plt.show()
```

Some tests are currently not passing. Is the case above one of the tests that don't pass? If not, I would suggest to generalize the code above for any element and add tests.

**Comment by melonora** [comment]
This is not one of the tests that doesn't pass. The tests that do not pass are those tests in which resulting image is a bit smaller than the expected image or in case no expected image has been generated yet. I will check this example
