### ISSUE TITLE
Drawing shapes in napari_spatialdata  results in Z-Polygons that cannot be plotted with pl.render_shapes

### ISSUE THREAD

**Issue by pakiessling** [scverse/spatialdata-plot#230]
```
sdata.shapes["Test_shapes"].iloc[0]
> geometry    POLYGON Z ((477.545 825.718 19.000, 433.553 82....)
sdata.pl.render_shapes("Test_shapes").pl.show()
>ValueError: 'vertices' must be 2D with shape (N, 2), but your input has shape (19, 3)
-----
anndata             0.10.6
geopandas           0.14.3
matplotlib          3.8.3
napari_spatialdata  0.3.1
pandas              2.2.1
session_info        1.0.0
shapely             2.0.3
spatialdata         0.0.16
spatialdata_plot    0.1.0
```

Heya,
Is this expected behavior?

Ty!

**Comment by LucaMarconato** [comment]
Hi @pakiessling, yes our data model currently assumes shapes (circles, polygons/multiploygons) to be 2D. I will add a check on the parser and validator in `ShapesModel` and explain this in a new tutorial notebook that I am currently preparing. I suggest to remove the `z` component. Please try and let me know if it works for you.

If you created the polygon as a napari-spatialdata annotation and you found that it included the `z` component by default please let as know. We had this problem in the past but it seemed to be fixed; I could look at it again.

**Comment by pakiessling** [comment]
I created the problematic polygon in napari-spatialdata. 
It came out like this after shift+e.
You mention "napari annotation". I created a new shape layer in napari but there seems to also be the option to create an annotation layer.
Is that different?

**Comment by LucaMarconato** [comment]
Thanks, I'll look into this. I suggest to remove the z component, replace the shapes object in-memory and proceed with the analysis. 

I will fix the napari behaviour; tracker here: https://github.com/scverse/napari-spatialdata/issues/218.

With "napari annotation" I was referring to the shape layer.

**Comment by pakiessling** [comment]
Perfect, thank you!

**Comment by LucaMarconato** [comment]
I fixed it with https://github.com/scverse/napari-spatialdata/pull/228 😊
