### ISSUE TITLE
Wrong pypi project link

### ISSUE THREAD

**Issue by aeisenbarth** [scverse/spatialdata-plot#233]
Clicking "Documentation" on https://pypi.org/project/spatialdata-plot/ leads to https://spatialdata.readthedocs.io/ which is a geographic library.

The correct link is https://spatialdata.scverse.org/projects/plot/en/latest/

I didn't find it in the repository, so it is probably in the project settings on the Pypi  website.

**Comment by LucaMarconato** [comment]
Thanks for reporting this, I checked the various repositories.

- the docs in spatialdata-io are correct
- @kevinyamauchi @timtreis you are maintainer of `spatialdata-plot` in `pypi`, can you please use this link for the docs: https://spatialdata.scverse.org/projects/plot/en/latest/index.html
- @kevinyamauchi @giovp can you please update the link in `spatialdata` in `pypi` to https://spatialdata.scverse.org/en/latest/
- @giovp can you please update the link to of `napari-spatialdata` in `pypi` to https://spatialdata.scverse.org/projects/napari/en/latest/notebooks/spatialdata.html

Thank you! Also please can you add me in `pypi` as a maintainer? Thanks.

**Comment by LucaMarconato** [comment]
Thanks @timtreis, I fixed it also in the other 2 repos.
