### ISSUE TITLE
background label color not respected.

### ISSUE THREAD

**Issue by melonora** [scverse/spatialdata-plot#241]
Seemingly the color of background labels is not respected. This is the output from the mibitof notebook:
![afbeelding](https://github.com/scverse/spatialdata-plot/assets/22346363/1ed1bf41-d826-4c94-b43d-5b8ec7d2a566)

I remember having fixed this issue before but somehow it got reintroduced now.

**Comment by timtreis** [comment]
It works as expected for `blobs`. When I load the data from disk, it shows that the f.e. the top area of `point_23` has the value `1`, whereas the background in the blobs dataset has the value `0`. Did we change that convention?

<img width="519" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/12818242/f035d431-0f06-456e-8736-7c0eca8acd8e">
<img width="443" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/12818242/bda1c56d-24ca-4a8f-9e2f-7111bd3780cd">

**Comment by LucaMarconato** [comment]
In that mibitof dataset several non-zero values are used for those large regions, it is therefore expected to show a random color. Closing the issue.
