### ISSUE TITLE
render_shapes() - problem with cmap alpha

### ISSUE THREAD

**Issue by roynov01** [scverse/spatialdata-plot#251]
The alpha doesn't work for me, what am I missing?
viridis = cm.get_cmap("viridis", 256)
colors = viridis(np.linspace(0, 0.8, 256))
colors[0, :] = [1, 1, 1, 0]
new_cmap = LinearSegmentedColormap.from_list("truncated_viridis", colors)

sdata_small.pl.render_images("Visium_HD_Mouse_Small_Intestine_full_image").pl.render_shapes(
        f"Visium_HD_Mouse_Small_Intestine_square_016um", color=gene_name, cmap=new_cmap).pl.show(
    coordinate_systems="global", title=gene_name, figsize=(10, 10))

![image](https://github.com/scverse/spatialdata-plot/assets/84639293/4af6f49f-1459-4f08-9140-2fe56f0eea43)

The alpha doesn't work even when I use custon cmap with low alpha all over:
![image](https://github.com/scverse/spatialdata-plot/assets/84639293/915a6b76-2d19-4572-b9b6-ab6cb79cb894)

**Comment by LucaMarconato** [comment]
Hi, it looks like that the reason is that the fix from this PR https://github.com/scverse/spatialdata-plot/pull/239 didn't make it to a release yet. I will cut a release now.

**Comment by LucaMarconato** [comment]
I made the release in `pip`, please let me know if this fixes your issue.

**Comment by Bioin-Mixologist** [comment]
Thankfully, after the update, it is now possible to display transparent colors.
```shell
pip install --upgrade spatialdata-plot==0.2.2
```
![upgrade](https://github.com/scverse/spatialdata-plot/assets/130979614/4ea59d8a-9d8a-48b6-a602-8905f2e6d60c)

However, i found exp maybe diiferent if chage get_cmap() follow the prompts, and prepare to open a new issue.
```python
The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ''matplotlib.colormaps[name]'' or ''matplotlib.colormaps.get_cmap(obj)'' instead.
viridis= cm.get cmap("viridis",256)
```
![newissue](https://github.com/scverse/spatialdata-plot/assets/130979614/e1abc047-7ace-496c-a02d-d59f7f3765e4)

**Comment by melonora** [comment]
Thanks for opening the new issue, given that the reason for this issue has been solved I will be closing this one. Currently we are in the process of going through all issues with the repositories related to SpatialData so we will address your new issue:)
