### ISSUE TITLE
"Artifact" when plotting labels with `outline=True`

### ISSUE THREAD

**Issue by clwgg** [scverse/spatialdata-plot#252]
I've come across a weird "artifact" that can be triggered when plotting labels with `outline=True`:

```python
sdata.pl.render_labels(outline=False).pl.show()
```
![main-1](https://github.com/scverse/spatialdata-plot/assets/26062675/c92ef9b2-23ed-4e5b-ad23-1dd0680bbc1c)

```python
sdata.pl.render_labels(outline=True).pl.show()
```
![main-2](https://github.com/scverse/spatialdata-plot/assets/26062675/d9297520-96e4-44c5-be3d-ef5cd446a37d)

It's a little hard to see, but in the 2nd figure, there appears to be some kind of "shade" in the top-left corner of the plot.

I went digging a bit for possible causes -- please see the PR linked below for a potential fix.

**Comment by timtreis** [comment]
Hey @clwgg, 

sorry for the late response! I think the "shade" you're seeing is some improperly transformed data layer, probably a difference in scale? 

Could you try to reproduce your error with the code from https://github.com/scverse/spatialdata-plot/pull/323? I've included several fixes to `render_labels` there, amongst which I also changed the outline logic to be purely based on `outline_alpha` since 0/1 there would be equivalent to `outline = True/False`

**Comment by clwgg** [comment]
Hi @timtreis! I'm happy to report that I don't observe the artifact anymore with the current `main`.

It also appears to fix the other observations I had over at https://github.com/scverse/spatialdata-plot/pull/253, except for the use case of plotting labels without alpha at all (`render_labels(outline_alpha=1.0, fill_alpha=1.0)`), but I see you're already fixing that [elsewhere](https://github.com/scverse/spatialdata-plot/pull/336), so I believe both this issue, as well as my PR (and possibly the other issue I linked in the PR) can be closed! 🎉

**Comment by timtreis** [comment]
Hey @clwgg,

happy to hear that the issue is already partially solved!

Could you elaborate on 
>  except for the use case of plotting labels without alpha at all (render_labels(outline_alpha=1.0, fill_alpha=1.0)

With the current code, this would be equivalent to `render_labels(fill_alpha=1.0)` since any border would only ever be inside the label anyway. I just found that out like a minute ago, but here's the comment I added for clarification:
![image](https://github.com/user-attachments/assets/986b34cd-3e18-464d-b356-d04e9867ed48)

**Comment by clwgg** [comment]
hmm, that's a fair point! I suppose it depends on what we think the [zorder](https://matplotlib.org/stable/gallery/misc/zorder_demo.html) of a labels' fill and outline should be. AFAIK, in a matplotlib scatterplot for example, the outline of a marker is drawn on top of the fill, so in a case without any transparency, I would expect to still see the outline on top of the fill, even if it's fully contained within the label.

**Comment by timtreis** [comment]
![image](https://github.com/user-attachments/assets/d75309f8-d608-4b63-a5f9-9d12315d8006)
Without any alpha you theoretically still see the border but I think that's just an artifact from the resolution of the plot.

**Comment by clwgg** [comment]
Interesting! To be honest, the main use case I'm envisioning is if I was coloring the labels based on some continuous variable and didn't want to use transparency (maybe to increase contrast), but still would like the individual labels to be distinguishable by adding an outline, similar to the [image](https://private-user-images.githubusercontent.com/26062675/325029801-f6a7ac13-f186-47ff-a07d-bd410b4cf298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODA4MDcsIm5iZiI6MTcyNDg4MDUwNywicGF0aCI6Ii8yNjA2MjY3NS8zMjUwMjk4MDEtZjZhN2FjMTMtZjE4Ni00N2ZmLWEwN2QtYmQ0MTBiNGNmMjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIxMjgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MzAyZTMwM2Y3NGJkMjFhZmVmY2YyZTU0ZDdiMzc2MjQyZjMxZDc1ZmVmNTBiNTEwMWNmNDgwOGI1ZmY1Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x8RRgijOPAaSUMHQ964XbMMcxWBf-z4Q1sfOQt1YqHU) in the PR I linked above, or something like 
[this](https://github.com/user-attachments/assets/68f16d27-6718-4491-bd9d-77a69ae295e5).

But I can see that allowing this opens potential cans of worms, especially in combination with `contour_px`, and I suppose one could still force a similar behaviour with something like `render_labels(outline_alpha=1.0, fill_alpha=.99)`...

**Comment by timtreis** [comment]
You could theoretically just call `render_labels` twice to enable that usecase:

![image](https://github.com/user-attachments/assets/554a181f-611a-4c13-a92e-34e1d1e9ac6d)

**Comment by clwgg** [comment]
good point, thanks! 👍

**Comment by timtreis** [comment]
Seems to be solved :) Thanks @clwgg !
