### ISSUE TITLE
Plotting with random colours is slow

### ISSUE THREAD

**Issue by timtreis** [scverse/spatialdata-plot#28]
### Description of feature

When plotting f.e. labels with a random colours for each label, the code is very slow. That's because for every single label, first the infill and then the border is added to the plot. So that's `n_labels * 2` iterations. 

![image](https://user-images.githubusercontent.com/12818242/229480413-46793dc6-f7af-43d1-9c4a-6d38bd9794c2.png)

Instead we could go "pseudo-random" with the colors and just generate 20-30 random ones. That way, we'd go down to `n_distinct_colours * 2` iterations.

**Comment by sagar87** [comment]
I know how to make this quick. I'll do a PR asap.
