### ISSUE TITLE
Extract image RGB information per Visium HD bin

### ISSUE THREAD

**Issue by sunyumail93** [scverse/spatialdata-plot#284]
Hello, I posted a question previously in Seurat (https://github.com/satijalab/seurat/issues/9036) but they don't have bandwidth to implement this feature. Since squidpy has a similar function (https://squidpy.readthedocs.io/en/stable/api/squidpy.im.calculate_image_features.html), would it be possible to perform a similar analysis in spatialdata? Or can we run that squidpy function on the spatialdata object? I would like to extract the image (H&E or fluorescence) features, such as the RGB color information for each Visium HD bin. Thank you!

**Comment by melonora** [comment]
Hi @sunyumail93, sorry for getting back to you a bit late! We are currently having discussions for implementing this among others, but can't really give you a timeline at the moment. @giovp I think you know better than me whether there is a way to hack around to allow this functionality to run right now. Could you provide some insights?

**Comment by giovp** [comment]
Hi @sunyumail93 , a workaround could be to take the image and label elements from spatialdata and create an imagecontainer object. Generate the features from squidpy and then save the results back to spatialdata. Indeed we understand that this is a much needed functionality and that we are having discussions within the team to start supporting this.

**Comment by sunyumail93** [comment]
Thank you both for your response! I look forward to the implementation of this feature.

**Comment by timtreis** [comment]
@sunyumail93 thank you for the suggestions! I'll keep track of this workstream over at https://github.com/scverse/squidpy/issues/850
