### ISSUE TITLE
Legend wrong for categorical: test failing on "data CI" but not on GitHub.

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#292]
The CI from main is green, still, the following test fails in the data CI:

```
FAILED tests/pl/test_render_labels.py::TestLabels::test_plot_label_categorical_color[blobs_labels] - AssertionError: Error: Image files did not match.
FAILED tests/pl/test_render_labels.py::TestLabels::test_plot_label_categorical_color[blobs_multiscale_labels] - AssertionError: Error: Image files did not match.
```

I checked the artifacts, and I see this.
Expected:
![image](https://github.com/user-attachments/assets/b890a37a-1546-4ebc-b570-b1a95b3070ff)

Actual:
![image](https://github.com/user-attachments/assets/7ebe15ef-9df6-4a77-bbb3-093b47c5e766)

@melonora could you please have a look at this?

**Comment by melonora** [comment]
Yeah would be after the weekend though

**Comment by LucaMarconato** [comment]
No problem, thanks 😊
