### ISSUE TITLE
Wrong colors when using `method='datashader'`

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#311]
When `method=datashader` is used the colors that are produced are wrong. Strangely the colorbar is correct. Initially I though this was due to the choice of the `agg` function when each pixel of the rasterized image was overlapping multiple elements. But since this problem appears also for large bins, which span several pixels, and since no border effect is observed, I believe that the problem lies elsewhere.

Code to reproduce.
```python
##
import spatialdata_plot
from spatialdata import read_zarr, bounding_box_query
import matplotlib.pyplot as plt

f = 'spatialdata-sandbox/visium_hd_3.0.0_io/data.zarr'

sdata = read_zarr(f)
sdata

for table in sdata.tables.values():
    table.var_names_make_unique()

##
crop = lambda x: bounding_box_query(
    x, min_coordinate=[5000, 7000], max_coordinate=[10000, 12000], axes=("x", "y"), target_coordinate_system="global"
)
gene_name = "AA986860"

##
crop(sdata).pl.render_shapes('Visium_HD_Mouse_Small_Intestine_square_016um', color=gene_name).pl.show(coordinate_systems='global')
plt.show()

##
crop(sdata).pl.render_shapes('Visium_HD_Mouse_Small_Intestine_square_016um', color=gene_name, method='datashader').pl.show(coordinate_systems='global')
plt.show()
```

**Comment by LucaMarconato** [comment]
This is the first plot, the correct one (`method='matplotlib'`).
![image](https://github.com/user-attachments/assets/8f0a9c69-9f0e-4941-b16a-6de60db1d0cc)

This is the second plot, the wrong one (`method='datashader'`).
![image](https://github.com/user-attachments/assets/7de3b647-93a2-40f6-8b6f-d4e9d0866d5e)

**Comment by Sonja-Stockhaus** [comment]
Thanks @LucaMarconato! The aggregation is correct, but `shade()` uses an equi-width histogram for coloring per default, while we want the linear version. Now it looks like this using datashader

![grafik](https://github.com/user-attachments/assets/b1cdf562-1387-475e-9680-6103bd7e2c5a)

**Comment by LucaMarconato** [comment]
Thanks for checking into this!

**Comment by LucaMarconato** [comment]
Update: different aggregation functions require different colorbars, we are working into this.
