### ISSUE TITLE
Point sizes disagree between matplotlib and datashader

### ISSUE THREAD

**Issue by Sonja-Stockhaus** [scverse/spatialdata-plot#315]
For plotting points with matplotlib, we use the `s` argument of `scatter()`. The *square root* of `s` specifies the width and height of the markers in points.

In the datashader approach, we use `ds.tf.spread(agg, px=px)` to regulate the size of the markers. Here, `px` is calculated like this: `px = int(np.round(np.sqrt(render_params.size)))`, to make the behavior agree to the matplotlib approach.

Problem: If you alter the `dpi` in `pl.show()`, the point size of the datashader points remains the same, whileit changes for matplotlib, leading to different sizes:

`dpi=100`, mpl=blue, ds=white
```python
blob.pl.render_points(element="blobs_points", size=400, color="blue").pl.render_points(element="blobs_points", size=400, color="white", method="datashader", alpha=1).pl.show(dpi=100)
``` 
![grafik](https://github.com/user-attachments/assets/dee3c4cb-1636-4ef4-bd6a-a58ad38b8017)

`dpi=200`, mpl=blue, ds=white
```python
blob.pl.render_points(element="blobs_points", size=400, color="blue").pl.render_points(element="blobs_points", size=400, color="white", method="datashader", alpha=1).pl.show(dpi=200)
``` 
![grafik](https://github.com/user-attachments/assets/e20a4120-28ab-446e-9232-f1cc2a5b04c8)

`dpi=50`, ds=blue, mpl=white (note: colors and order swapped!)
```python
blob.pl.render_points(element="blobs_points", size=400, color="blue", method="datashader", alpha=1).pl.render_points(element="blobs_points", size=400, color="white").pl.show(dpi=50)
``` 
![grafik](https://github.com/user-attachments/assets/9371db9b-2f02-4d37-924b-945727dd7e38)

**Comment by Sonja-Stockhaus** [comment]
Btw I think for `dpi=100`, the mpl points are *slightly* larger than the ds points because marker edges are drawn (default linewidth = 1.5), see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html.
However, this is not the actual problem

**Comment by Sonja-Stockhaus** [comment]
Solution for now: use `dpi/100` as a factor to adapt `px` to varying `dpi`

**Comment by Sonja-Stockhaus** [comment]
Now it looks like this, for dpi `[50, 100, 200, 300]` using `blob.pl.render_points(element="blobs_points", size=400, color="blue").pl.render_points(element="blobs_points", size=400, color="yellow", method="datashader", alpha=1).pl.show(dpi=100)`
Should be correct imo

(matplotlib points bluse, datashader yellow)
![grafik](https://github.com/user-attachments/assets/c1bcdd6c-73a6-453d-90f2-4ac2c4899241)
![grafik](https://github.com/user-attachments/assets/4bf6f067-ffaf-4a9b-8306-266e08aa9956)
![grafik](https://github.com/user-attachments/assets/56838388-ecdb-4a5b-a8e4-7d1d744ee36b)
![grafik](https://github.com/user-attachments/assets/db44b26e-0289-46cf-932b-2d2c69fff197)

**Comment by LucaMarconato** [comment]
Looks good to me. The tiny pixel offset is probably inevitable and acceptable.
