### ISSUE TITLE
sdata.pl.render_points() works wiered

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/spatialdata-plot#320]
Hi,
I find `sdata.pl.render_points()` works wiered when using the default datashader method. Maybe there there something wrong when processing the coordinates for datashader.
The output of `sdata.pl.render_points("transcripts", color="feature_name", groups="A2M", size=100, palette="orange").pl.show()`:
![image](https://github.com/user-attachments/assets/eaddb7b7-8a43-4e0c-b668-399b566a48ae)

The output of `sdata.pl.render_shapes("cell_boundaries", color="A2M").pl.render_points("transcripts", color="feature_name", groups="A2M", size=100, palette="orange").pl.show()` is similiar, the coordinate of transcripts is global:
![image](https://github.com/user-attachments/assets/7d632183-db56-4152-9ca7-4f6fab925934)

The output of `sdata.pl.render_shapes("cell_boundaries", color="A2M").pl.render_points("transcripts", color="feature_name", groups="A2M", method="matplotlib", palette="orange").pl.show()` worked well:
![image](https://github.com/user-attachments/assets/6241a5e0-9d05-442e-a0bb-39ac64520ded)

Here is my spatialdata object:
![image](https://github.com/user-attachments/assets/f41d4921-2f2b-46ff-935c-53b68026c95f)

**Comment by LucaMarconato** [comment]
You are correct, there is problem with datashader which I reported here https://github.com/scverse/spatialdata-plot/issues/291 and which is currently being worked on. In the issue I posted a workaround (transform the points data before plotting).

Regarding the axis name, we do not plan to automatically write `spatial`; but if you are interested it you can for instance do
```python
import matplotlib.pyplot as plt

plt.figure()
ax = plt.gca()
sdata.pl.render_shapes(...).pl.show(ax=ax)
ax.set_xlabel('X-axis label')
ax.set_ylabel('Y-axis label')
plt.show()
```

**Comment by LucaMarconato** [comment]
CC @timtreis
