### ISSUE TITLE
Unable to plot categorical columns

### ISSUE THREAD

**Issue by gboscagli** [scverse/spatialdata-plot#328]
Hi all,
I'm finding troubles using `spatialdata-plot` static visualization on my categorical annotations. I'm using this [public CosMx dataset](https://kero.hgc.jp/Breast_Cancer_Spatial.html), I performed standard preprocessing and a simple Leiden clustering with dedicated `Scanpy` functions. However, this error is thrown:

**CHUNK**
```
fig, ax = plt.subplots(ncols=1, nrows=1, figsize=(20, 20))
(
    sdata.pl.render_images(element="2_image")
    .pl.render_labels(element="2_labels", color="leiden", fill_alpha=1, contour_px=10)
    .pl.show(coordinate_systems=["2"], ax=ax)
)
```

**TRACEBACK**
```
{
	"name": "ValueError",
	"message": "buffer source array is read-only",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[28], line 5
      1 fig, ax = plt.subplots(ncols=1, nrows=1, figsize=(20, 20))
      2 (
      3     sdata.pl.render_images(element=\"2_image\")
      4     .pl.render_labels(element=\"2_labels\", color=\"leiden\", fill_alpha=1, contour_px=10)
----> 5     .pl.show(coordinate_systems=[\"2\"], ax=ax)
      6 )

File c:\\Users\\Gabriele\\anaconda3\\envs\\cell2loc_env\\Lib\\site-packages\\spatialdata_plot\\pl\\basic.py:937, in PlotAccessor.show(self, coordinate_systems, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, na_in_legend, colorbar, wspace, hspace, ncols, frameon, figsize, dpi, fig, title, share_extent, pad_extent, ax, return_ax, save)
    925                 _maybe_set_colors(
    926                     source=sdata[table],
    927                     target=sdata[table],
    928                     key=params_copy.color,
    929                     palette=params_copy.palette,
    930                 )
    932         rasterize = (params_copy.scale is None) or (
    933             isinstance(params_copy.scale, str)
    934             and params_copy.scale != \"full\"
    935             and (dpi is not None or figsize is not None)
    936         )
--> 937         _render_labels(
    938             sdata=sdata,
    939             render_params=params_copy,
    940             coordinate_system=cs,
    941             ax=ax,
    942             fig_params=fig_params,
    943             scalebar_params=scalebar_params,
    944             legend_params=legend_params,
    945             rasterize=rasterize,
    946         )
    948 if title is None:
    949     t = cs

File c:\\Users\\Gabriele\\anaconda3\\envs\\cell2loc_env\\Lib\\site-packages\\spatialdata_plot\\pl\\render.py:779, in _render_labels(sdata, render_params, coordinate_system, ax, fig_params, scalebar_params, legend_params, rasterize)
    765 color_source_vector, color_vector, categorical = _set_color_source_vec(
    766     sdata=sdata_filt,
    767     element=label,
   (...)
    774     table_name=table_name,
    775 )
    777 if (render_params.fill_alpha != render_params.outline_alpha) and render_params.contour_px is not None:
    778     # First get the labels infill and plot them
--> 779     labels_infill = _map_color_seg(
    780         seg=label.values,
    781         cell_id=instance_id,
    782         color_vector=color_vector,
    783         color_source_vector=color_source_vector,
    784         cmap_params=render_params.cmap_params,
    785         seg_erosionpx=None,
    786         seg_boundaries=render_params.outline,
    787         na_color=render_params.cmap_params.na_color,
    788     )
    789     _cax = ax.imshow(
    790         labels_infill,
    791         rasterized=True,
   (...)
    796         zorder=render_params.zorder,
    797     )
    798     _cax.set_transform(trans_data)

File c:\\Users\\Gabriele\\anaconda3\\envs\\cell2loc_env\\Lib\\site-packages\\spatialdata_plot\\pl\\utils.py:747, in _map_color_seg(seg, cell_id, color_vector, color_source_vector, cmap_params, seg_erosionpx, seg_boundaries, na_color)
    745     if isinstance(na_color, tuple) and len(na_color) == 4 and np.any(color_source_vector.isna()):
    746         cell_id[color_source_vector.isna()] = 0
--> 747     val_im: ArrayLike = map_array(seg, cell_id, color_vector.codes + 1)
    748     cols = colors.to_rgba_array(color_vector.categories)
    750 else:

File c:\\Users\\Gabriele\\anaconda3\\envs\\cell2loc_env\\Lib\\site-packages\\skimage\\util\\_map_array.py:72, in map_array(input_arr, input_vals, output_vals, out)
     70 input_vals = input_vals.astype(input_arr.dtype, copy=False)
     71 output_vals = output_vals.astype(out.dtype, copy=False)
---> 72 _map_array(input_arr, out_view, input_vals, output_vals)
     73 return out

File _remap.pyx:10, in skimage.util._remap._map_array()

File <stringsource>:663, in View.MemoryView.memoryview_cwrapper()

File <stringsource>:353, in View.MemoryView.memoryview.__cinit__()

ValueError: buffer source array is read-only"
}
```

If this can be of any help, when I launch `Napari` the leiden column is present but completely ignored in the visualization when selected. Moreover, I found the same behavior using another public dataset, the `Lung5-Rep2` provided by Nanostring, and also manually adding external cell type annotations as `obs` column in the table of my `SpatialData` object. I wasn't able to reproduce the bug in `blobs` dataset, as it all works as expected, but since I took very few steps from the raw dataset it seemed worth to me to report the error with the community.

**Comment by timtreis** [comment]
Hey @gboscagli, thank you for reporting! 

It seems that this issue comes from outside of `spatialdata` since `skimage` complains that your data is "read-only". You can verify this with

```
print(your_array.flags)
```

One thing you could try is saving the data out to a `.zarr` file and then re-reading it. Let me know if the bug persists or can be traced back to `spatialdata`

**Comment by gboscagli** [comment]
> One thing you could try is saving the data out to a .zarr file and then re-reading it. Let me know if the bug persists or can be traced back to spatialdata

I followed your instructions and now the static plotting works! So I guess it's something dataset-dependent or to be investigated on `skimage` side in order to avoid the re-reading of all my datasets before analyzing them.

**Comment by LucaMarconato** [comment]
@gboscagli did this fix plotting in napari too?

**Comment by gboscagli** [comment]
@LucaMarconato yes, it all seems to work.

**Comment by MiTPenguin** [comment]
Hi @gboscagli and @timtreis,

I'm running into the same issue with my constructed sdata objects, and same thing when I tried it with the cosmx data.

What did the "your_array" in this case pointed to? the labels layers are all xarray.DataArray, which doesn't have the flag attributes.

And saving it out to zarr: is it just saving it to a separate zarr store? even if we read it from a zarr (downloaded) store to begin with?

**Comment by MiTPenguin** [comment]
@timtreis Also, the issue was discussed [here in skimage](https://github.com/scikit-image/scikit-image/issues/6378#issuecomment-2339047581).

Not sure where the cython fix would be applied.

**Comment by gboscagli** [comment]
@MiTPenguin 
I actually didn't try to print flag attributes, I saved my dataset as a `zarr` store straightforward. And yes, for me it worked just by saving the public `CosMx` dataset (read with `spatialdata_io.cosmx`) as a zarr store and re-read it with `spatialdata.read_zarr`.
You can try to save a duplicate of the zarr store and read this copy. Obviously, this is just a workaround: the issue remains on `skimage` side.

**Comment by MiTPenguin** [comment]
@gboscagli @LucaMarconato 

Unfortunately this has not worked for me.

could you let me know what version of `skimage` and `spatialData-plot` that you are using?

**Comment by gboscagli** [comment]
@MiTPenguin 
`scikit-image==0.24.0`
`spatialdata==0.2.2`

**Comment by timtreis** [comment]
@gboscagli and which version of `spatialdata-plot`?

**Comment by gboscagli** [comment]
@timtreis 
`spatialdata-plot==0.2.4`

**Comment by timtreis** [comment]
Could you update to 0.2.6 and see if the bug persists?

**Comment by gboscagli** [comment]
With spatialdata-plot 0.2.6 it works even with the native `CosMx` dataset, without the intermediate step of the zarr store!

I encountered a different issue: I tried to set the colors of the categorical column with a dict in uns, but they are not recognized as `Napari-SpatialData` does. Don't know if this is implemented for static plotting also.

`ValueError: Expected palette to be of length `18`, found `1`. Removing the colors in `adata.uns` with `adata.uns.pop('InSituType_Simple_colors')` may help.`

**Comment by timtreis** [comment]
Happy to hear that it works with `0.2.6`! 

> I tried to set the colors of the categorical column with a dict in uns, but they are not recognized as Napari-SpatialData does. 

We do check for the existence of the `XYZ_colors` dict that f.e. `scanpy` would generate. So if you'd do `sdata.pl.render_shapes(color="my_col")`, it should use to colors from `adata.uns["my_col_colors"]` if present. Is this what you meant?

**Comment by gboscagli** [comment]
> We do check for the existence of the XYZ_colors dict that f.e. scanpy would generate. So if you'd do sdata.pl.render_shapes(color="my_col"), it should use to colors from adata.uns["my_col_colors"] if present. Is this what you meant?

Yes. I have the `adata.uns["my_col_colors"]` that is a dictionary with categories as keys and HEX color codes as values. The suffix _colors is set correctly.

```
sdata["table"].uns["InSituType_Simple_colors"] = {
    'Blood ECs': '#e94b3f',
    'DCs': '#a0c8f0'
    ...}
```

```
fig, ax = plt.subplots(ncols=1, nrows=1, figsize=(50, 50))
(
    sdata.pl.render_images(element="2_image")
    .pl.render_labels(element="2_labels", color="InSituType_Simple", fill_alpha=1, contour_px=10)
    .pl.show(coordinate_systems=["2"], ax=ax)
)

ax.legend(
    loc='center left', 
    bbox_to_anchor=(1, 0.5),  # Place the legend outside the plot
    fontsize=70
)
```

Forget about the `ValueError` mentioned before, it was my fault. Colors in the uns dict are just "ignored", and I think there may be some type mismatch. `InSituType_Simple` is a categorical column.
It could just be something on the dataset side, since I guess this is a very solid method coming from `Scanpy`.
