### ISSUE TITLE
Coloring labels by a continuous variable appears to be broken (labels associated with wrong colors)

### ISSUE THREAD

**Issue by clwgg** [scverse/spatialdata-plot#342]
My testing code:
``` python
import spatialdata as sd
import spatialdata_plot
import matplotlib.pyplot as plt
import numpy as np

sdata = sd.datasets.blobs()
sdata.pl.render_labels("blobs_labels", color="channel_0_sum").pl.show()
```

Previously (here I used commit c6575e2f5e49b495f97b6c7fc08fe9c16e0684d7) this would look something like this:
<img src="https://github.com/user-attachments/assets/90db5bfc-6ebf-4549-8ae4-1ae2a616b199" width="350">

However, since e97a7fcb86762f66713c4cf0047d8353fc61984c, this looks like this:
<img src="https://github.com/user-attachments/assets/a6f5101c-820b-4e72-9e9c-324c472be883" width="350">

Just to make sure that the first plot is correct, I extracted the labels where `channel_0_sum` is high, which shows that the two labels shown in yellow and green in the first plot are indeed the ones with the highest values:
``` python
highid = sdata.table.obs[sdata.table[:,'channel_0_sum'].X.toarray() > 1000].instance_id
plt.imshow(np.isin(sdata['blobs_labels'], highid))
```

<img src="https://github.com/user-attachments/assets/2f13d651-345d-41ad-b250-f467db4770bc" width="350">

**Comment by timtreis** [comment]
Thank you for the issue @clwgg, will fix now
