### ISSUE TITLE
Typehints in docstring of functions is redundant and removed by readthedocs anyway

### ISSUE THREAD

**Issue by timtreis** [scverse/spatialdata-plot#37]
### Report

see title

**Comment by timtreis** [comment]
@sagar87 when you're working on the docs anyway, maybe you could also remove the typehints from the docs? Sphinx apparently generates them from the code, so having them in two places is redundant and they'd probably get out of sync really fast

**Comment by sagar87** [comment]
#44 should fix the issue.
