### ISSUE TITLE
`render_labels` returns uniform color in large images

### ISSUE THREAD

**Issue by AdnanAbouelela** [scverse/spatialdata-plot#373]
Hi,

I'm embedding the segmentation output of Cellpose into a SpatialData object as a labels SpatialElement. In my case I'm working with a 2D segmentation mask, where 0 corresponds to the background and pixels belonging to the same cell are indexed with the same number. 

I noticed, that if I want to visualize all masks using `sdata.pl.render_labels().pl.show()`, the masks appear in a pink color. However, when I crop the object to contain only a particular (small enough) FOV, the cells are visualized nicely using random colors. This issue is related to the size of the image, not the number of cell masks to be plotted. The following is a minimal reproducible example:

```python
import numpy as np
from spatialdata import SpatialData
from spatialdata.models import Labels2DModel
import spatialdata_plot

np.random.seed(seed = 0)
n = [11, 101, 1001, 1501, 2001]

fig, axs = plt.subplots(nrows = 1, ncols = len(n), figsize = (15,15))
for ax_ind, l in enumerate(n):

    # Create a random mask (simulating a cellpose segmentation output)
    # Every number corresponds to a cell index
    mask = np.random.randint(1, l**2 + 1, size=(l, l))

    # Add a big cell in the middle that should be visible in larger images
    center = (l // 2) + 1
    start = int(center - 0.5 * center)
    end = int(center + 0.5 * center) - 1

    uniform_value = l**2 + 1 
    mask[start:end, start:end] = uniform_value

    # Create a SpatialData object
    mask_parsed = Labels2DModel.parse(mask)
    labels = {"mask": mask_parsed}
    sdata = SpatialData(labels = labels)

    sdata.pl.render_labels().pl.show(ax = axs[ax_ind])
    axs[ax_ind].set_title(f"l = {l}")
    axs[ax_ind].axis("off")
``` 

![Image](https://github.com/user-attachments/assets/6a6b33ac-e960-4188-9efd-b6f1aaa63da2)

Somewhere in between ~1500^2 and ~2000^2 pixels, the function does not render the labels properly anymore. As all my images are larger than that, I currently can't render all labels (there are workarounds though). Also, as a sidenote, in the `l=11` condition, it is visible that the pixels are shifted by half a pixel, which is probably related to #216.

I am working with:
python = 3.12.3
spatialdata = 0.2.2
spatialdata_plot = 0.2.4

It would be great if there was a fix for that. I appreciate the help & thanks in advance!

**Comment by clwgg** [comment]
I've observed this previously as well but on my end this was fixed by subsequent releases of `spatialdata_plot`, so it might be worth to update to a more recent release and see if the problem persists.

**Comment by AdnanAbouelela** [comment]
I updated `spatialdata_plot` to `0.2.7.dev6+g80c6f77` and now it works, thanks!
