### ISSUE TITLE
Missing visualizations tutorials in documentation

### ISSUE THREAD

**Issue by ConstensouxAlexis** [scverse/spatialdata-plot#382]
Hi !
It seems that most of the tutorials in the "Visualizations" part got removed (including Technology focus: Xenium and Technology focus: Visium HD). Is it still possible to have access to these tutorials ?
Thank you very much !

**Comment by melonora** [comment]
Hi @ConstensouxAlexis , it should be fixed now. We had a downgrade with new release and not updating the docs submodule so a post release has been created that fixes this.
