### ISSUE TITLE
why `render_channels` is a separate method and it's not an argument in the `render_image` method?

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata-plot#46]
### Report

wonder if it could just be an argument

**Comment by sagar87** [comment]
Yes good point, Tim and I already discussed that. The `render_channels` method currently handles (unnormalised) multichannel images (usually with more than 3 channels). This is useful for CODEX/IMC type image data in which you often have 50+ markers/channels. Here you are often interested in visualising 1-5 channels with different colors and thus you'd need to first select the appropriate channels and assign then colors to them. 

One question concerns at which point we want the user to select channels. Currently, this is done in `pl.render_channels`, e.g.

```
sdata.pl.render_channels(channels=[1,2,3], colors=['blue', 'red', 'green']).pl.show()
```

but perhaps more consistent with our `.pp` preprocessing logic would be to enforce something like this

```
sdata.pp.get_elements('image1', channels=[1,2,3]).pl.render_channels(['blue', 'red', 'green']).pl.show()
```

or even

```
sdata.pp.get_elements('image1').pp.get_channels([1,2,3]).pl.render_channels(['blue', 'red', 'green']).pl.show()
```

Do we have a preference regarding that ?

Generally, for the sake of simple API, I am also in favour of refactoring the `pl.render_channels` into `pl.render_images`.

**Comment by giovp** [comment]
I think `render_images` should have `channels` and `cmap` arguments anyway so the channel selection should just be part of `render_images`
