### ISSUE TITLE
Consider using `NamedTuple` instead of dictionaries

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata-plot#48]
### Report

for example, here https://github.com/scverse/spatialdata-plot/blob/582c8379f2478d0e7bc0a7d4733d3cb6fa9af061/src/spatialdata_plot/pl/basic.py#L574-L582

and here https://github.com/scverse/spatialdata-plot/blob/582c8379f2478d0e7bc0a7d4733d3cb6fa9af061/src/spatialdata_plot/pl/basic.py#L372

named tuple are more suitable for this approach.

**Comment by sagar87** [comment]
What would be the advantage of using `namedtuples` ? To keep the `param` dictionaries immutable ?

**Comment by giovp** [comment]
actually doing everything with `dataclasses`. heads up, am doing big rewrite at #45 , it's gonna be prob too disruptive and you guys will hate me but please bear with me, we can discuss on tue
