### ISSUE TITLE
render_images() doesn't account for image translations

### ISSUE THREAD

**Issue by kevinyamauchi** [scverse/spatialdata-plot#53]
### Report

When working on https://github.com/scverse/spatialdata-notebooks/pull/13, I noticed that `render_images()` doesn't seem to account for translations being applied to images.

To reproduce:

```python
# https://s3.embl.de/spatialdata/spatialdata-sandbox/visium.zip
sdata = sd.read_zarr("visium.zarr")
sdata_ST8059048 = sdata.filter_by_coordinate_system("ST8059048")


cropped_sdata = sdata_ST8059048.query.bounding_box(
    axes=["x", "y"], min_coordinate=[8000, 12000], max_coordinate=[12000, 16000], target_coordinate_system="ST8059048"
)

# plot the cropped data
# the image will be at the origin and the shapes will be in the correct location
f, ax = plt.subplots(figsize=(7, 7))
cropped_sdata.pl.render_images().pl.render_shapes(color="Sox2").pl.show(ax=ax, colorbar=False)
```
![Screenshot 2023-04-13 at 23 31 50](https://user-images.githubusercontent.com/1120672/231887478-e511cf49-b737-4f2f-a8b5-60ed1fa1c3ae.png)

### Version information

I installed with `pip install git+https://github.com/scverse/spatialdata-plot.git`

**Comment by kevinyamauchi** [comment]
For reference, here is the cropped spots overlaid on the original spots

![Screenshot 2023-04-13 at 23 32 49](https://user-images.githubusercontent.com/1120672/231887651-bbd50b98-0302-4b87-b36f-fc0df0ff70f2.png)

**Comment by timtreis** [comment]
I merged the PR that fixed the translation fairly late, could you verify that it is still an issue with your data? Not sure if your issue arose before or after the merge

**Comment by kevinyamauchi** [comment]
Hey @timtreis ! I still see this issue on main when I run [this notebook](https://gist.github.com/kevinyamauchi/338ba9f4a56eaf35d70ea88509758a0b).

<img width="556" alt="Screenshot 2023-04-20 at 17 07 30" src="https://user-images.githubusercontent.com/1120672/233408686-322b1dc6-6588-4a73-b27b-bc54b0ede636.png">

**Comment by timtreis** [comment]
FIxing that now 👌

**Comment by LucaMarconato** [comment]
I haven't looked at the implementation of `render_images()`, but if you call `rasterize()` inside it will handle transformations (including translations and multiscales in an efficient way).

**Comment by LucaMarconato** [comment]
Tried and works for me thanks. 

> I'll look into the function, but I really want to get the translation logic out of the plotting part 😓 It's creeping into other places like the extent function now.

True, the rasterization function will still give an object with a translation inside. Luckily this thing will be fixed with the new transformation refactoring (one will still have to parse the xarray coordinates at that point, but probably it will be handier than having a translation or a series of them).

Some more comments:
1. I run the code from the a Python console from the terminal and had to explicitly call `plt.show()` as `pl.show(colorbar=False)` was not creating the plot. 
2. I used the local data that should be identical to the one that I uploaded in S3 and I had this object here (notice that there are different coordinate systems). No idea why you have `ST8059048` and I don't. Tried redownloading the data but I still get the same.

```
SpatialData object with:
├── Images
│     ├── 'ST8059050_image': SpatialImage[cyx] (3, 2000, 1968)
│     └── 'ST8059051_image': SpatialImage[cyx] (3, 2000, 1963)
├── Shapes
│     ├── 'ST8059050_shapes': GeoDataFrame shape: (3497, 2) (2D shapes)
│     └── 'ST8059051_shapes': GeoDataFrame shape: (2409, 2) (2D shapes)
└── Table
      └── AnnData object with n_obs × n_vars = 5906 × 31053
    obs: 'in_tissue', 'array_row', 'array_col', 'annotating', 'library', 'spot_id'
    uns: 'spatialdata_attrs': AnnData (5906, 31053)
with coordinate systems:
▸ 'ST8059050', with elements:
        ST8059050_image (Images), ST8059050_shapes (Shapes)
▸ 'ST8059051', with elements:
        ST8059051_image (Images), ST8059051_shapes (Shapes)
```

**Comment by timtreis** [comment]
Re 1: https://github.com/scverse/spatialdata-plot/issues/58
Re 2: Yeah, that changed at some point while downloading data fresh. Looks the same to be but the numbers changed
