### ISSUE TITLE
Cannot plot multiple shapes elements

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#69]
Maybe I am doing something wrong. 

Using the code here: https://github.com/scverse/spatialdata-plot/issues/68
I don't see the circles rendered.

**Comment by LucaMarconato** [comment]
Tried out a few things, it seems that only one elements can be shown (the one appearing in the rightmost position in the plotting call).

This shows squares:
```
sdata.pl.render_shapes(element='c', na_color='y').pl.render_shapes(element='s', na_color='g').pl.render_points().pl.show()
```

while this shows circles:
```
sdata.pl.render_shapes(element='s', na_color='y').pl.render_shapes(element='c', na_color='g').pl.render_points().pl.show()
```

**Comment by LucaMarconato** [comment]
I am using this to plot now:
```
    ax = plt.gca()
    sdata.pl.render_shapes(element='s', na_color=(0.5, 0.5, 0.5, 0.5)).pl.render_points().pl.show(ax=ax)
    sdata.pl.render_shapes(element='c', na_color=(0.7, 0.7, 0.7, 0.5)).pl.show(ax=ax)
    plt.show()
```

Is it the intended behavior that `render_shapes()` should be called only once?

**Comment by timtreis** [comment]
No, that was a shortcut we took a million years ago. It should render all of them unless manually specified. I'll fix/add this functionality now.
