### ISSUE TITLE
Extent of axes dependent of order of points being shown

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata-plot#82]
Changing the order of what is being rendered may alter the extent being shown in the plot.

Here below is not a way to reproduce the bug because it would be laborious, but it shows an example of what is going on. This code
```python
        import matplotlib.pyplot as plt
        import spatialdata_plot

        # otherwise pre-commits will remove the "unused" import
        _ = spatialdata_plot

        ax = plt.gca()
        sdata.pl.render_shapes(element="by_polygons", na_color=(1.0, 0.7, 0.7, 0.5)).pl.show(ax=ax)
        sdata.pl.render_shapes(element="by_circles", na_color=(1.0, 0.7, 0.7, 0.5)).pl.show(ax=ax)
        sdata.pl.render_shapes(element="values_polygons", color="categorical_in_obs").pl.show(ax=ax)
        sdata.pl.render_shapes(element="values_circles", color="categorical_in_obs").pl.show(ax=ax)
        sdata.pl.render_points(color="categorical_in_ddf", size=10.0, palette="tab10").pl.show(ax=ax)
        # sdata.pl.render_shapes(element="values_circles", color="categorical_in_obs").pl.show(ax=ax) # <- this line is identical to the one 2 lines above!
        plt.show()
```
gives this plot:
<img width="608" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/2664412/c363799a-c323-4be1-b5e7-1c0bbf067726">

If we uncomment the last line, we get this plot instead:
<img width="507" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/2664412/a68e9633-fd8b-45e5-a42f-b5fff458219b">

If we plot only the line that is commented in the code above, this is shown:
<img width="499" alt="image" src="https://github.com/scverse/spatialdata-plot/assets/2664412/4e445073-ff67-47bc-ae6e-a0e73ccc9548">

Expected behaviors:
1) the final extent should not dependent of the order of elements being plot
2) the expected extent is the screenshots above doesn't fit the actual extent of the data

**Comment by LucaMarconato** [comment]
Note: I didn't look at the extent code but I saw a few PRs modifying it. If the problem arises because of edges cases of coordinate transformations I am happy to help refactoring the `get_extent()` code inside `SpatialData`.

**Comment by LucaMarconato** [comment]
More details: I think the problem is in `render_points()`.

**Comment by timtreis** [comment]
Note from call with @LucaMarconato: When `axs` object is passed, check for current axes limit and, if needed, extend them but not overwrite.

**Comment by timtreis** [comment]
@LucaMarconato let's merge some of the other smaller PRs before I implement the extent-increment logic here

**Comment by timtreis** [comment]
@LucaMarconato can you try to reproduce your error?
